### ISSUE TITLE
ImportError help!

### ISSUE THREAD

**Issue by vtorrecillas** [nicolas-ivanov/tf_seq2seq_chatbot#24]
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from tf_seq2seq_chatbot.lib.train import train
  File "/home/vinicius_torrecillas/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 14, in <module>
    from tf_seq2seq_chatbot.lib.seq2seq_model_utils import create_model
  File "/home/vinicius_torrecillas/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 11, in <module>
    from tf_seq2seq_chatbot.lib import seq2seq_model
  File "/home/vinicius_torrecillas/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 28, in <module>
    from tensorflow.models.rnn.translate import data_utils
ImportError: No module named models.rnn.translate

how can i fix this?

**Comment by smsrikanthreddy** [comment]
from tf_seq2seq_chatbot.lib import data_utils
