### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by llSourcell** [nicolas-ivanov/tf_seq2seq_chatbot#3]
I get the following error when i attempt to train the network. Any ideas? I'm pretty sure all the dependencies are properly installed since the setup bash script worked. 

```
1482-sraval:tf_seq2seq_chatbot sraval$ python train.py
You are using the decoding_enhanced library!
Initializer Library -- Will add to this if necessary.
Unitary Linear has been imported
Preparing dialog data in /var/lib/tf_seq2seq_chatbot/data
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 4
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 4
Creating 4 layers of 2048 units.
use aggregation_method=2
/Library/Python/2.7/site-packages/tensorflow/python/ops/gradients.py:87: UserWarning: Converting sparse IndexedSlices to a dense Tensor with 163840000 elements. This may consume a large amount of memory.
  "This may consume a large amount of memory." % num_elements)
Created model with fresh parameters.
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 12, in main
    train()
  File "/Users/sraval/Desktop/yooo2/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 28, in train
    model = create_model(sess, forward_only=False)
  File "/Users/sraval/Desktop/yooo2/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 35, in create_model
    session.run(tf.initialize_all_variables())
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell3/GRUCell/Candidate/Linear/Bias': Could not satisfy explicit device specification '/gpu:3'
     [[Node: embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell3/GRUCell/Candidate/Linear/Bias = Variable[container="", dtype=DT_FLOAT, shape=[2048], shared_name="", _device="/gpu:3"]()]]
Caused by op u'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/MultiRNNCell/Cell3/GRUCell/Candidate/Linear/Bias', defined at:
  File "train.py", line 15, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 12, in main
    train()
  File "/Users/sraval/Desktop/yooo2/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 28, in train
    model = create_model(sess, forward_only=False)
  File "/Users/sraval/Desktop/yooo2/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 27, in create_model
    forward_only=forward_only)
  File "/Users/sraval/Desktop/yooo2/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 149, in __init__
    softmax_loss_function=softmax_loss_function)
  File "build/bdist.macosx-10.10-intel/egg/rnn_enhancement/seq2seq_enhanced.py", line 629, in model_with_buckets
    bucket_decoder_inputs) #nick pay attention here -- you added bucket_states
  File "/Users/sraval/Desktop/yooo2/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 148, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "/Users/sraval/Desktop/yooo2/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 112, in seq2seq_f
    feed_previous=do_decode)
  File "build/bdist.macosx-10.10-intel/egg/rnn_enhancement/seq2seq_enhanced.py", line 341, in embedding_attention_seq2seq
    temperature_decode = temperature_decode, temperature = temperature)
  File "build/bdist.macosx-10.10-intel/egg/rnn_enhancement/seq2seq_enhanced.py", line 259, in embedding_attention_decoder
    temperature = temperature)
  File "build/bdist.macosx-10.10-intel/egg/rnn_enhancement/seq2seq_enhanced.py", line 159, in attention_decoder
    cell_output, new_state = cell(x, hidden_state_input) #nick, changed this to your hidden state input
  File "build/bdist.macosx-10.10-intel/egg/rnn_enhancement/rnn_cell_enhanced.py", line 1149, in __call__
    cur_inp, new_state = cell(cur_inp, cur_state) #this replaces cur_inp to a differen input
  File "build/bdist.macosx-10.10-intel/egg/rnn_enhancement/rnn_cell_enhanced.py", line 520, in __call__
    c = tf.tanh(linear.linear([inputs, r * state], self._num_units, True))
  File "build/bdist.macosx-10.10-intel/egg/rnn_enhancement/linear_enhanced.py", line 68, in linear
    initializer=tf.constant_initializer(bias_start))
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 242, in get_variable
    trainable, collections)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 175, in get_variable
    self.reuse, trainable, collections)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 119, in get_variable
    collections=collections)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/variables.py", line 210, in __init__
    name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/state_ops.py", line 116, in variable_op
    container=container, shared_name=shared_name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 334, in _variable
    name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()
```

**Comment by nicolas-ivanov** [comment]
@llSourcell so, you have the following problem:

```
Could not satisfy explicit device specification '/gpu:3'
```

Are you sure that that your computer has 4 GPUs available? Looks like there are only 2 or them.

**Comment by llSourcell** [comment]
sorry thanks. No im running this on a macbook with 1 GPU. What should i modify so it runs on 1? is there a way for it to just run on a CPU?

**Comment by nicolas-ivanov** [comment]
The easiest way to do that is to modify `tf_seq2seq_chatbot/configs/config.py`. There you need to set `num_layers` to 1:

``` python
tf.app.flags.DEFINE_integer('num_layers', 1, 'Number of layers in the model.')
```

In this case only one GPU will be used if its available. And if it's not, tensorflow will make sure to use your CPU.

In case you are faced with the following error

```
TypeError: unsupported operand type(s) for /=: 'Tensor' and 'Tensor'
```

check that you are using tensorflow 0.6.0

**Comment by llSourcell** [comment]
Thanks for the reply. Now I get

``` bash
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/GRUCell/Candidate/Linear/Bias': Could not satisfy explicit device specification '/gpu:0'
```

**Comment by nicolas-ivanov** [comment]
Seems like tensorflow tries to hook up your GPU but fails. Please post the full log output here.
Also what tensorflow version are you using? Is it GPU-enabled?

**Comment by geckom** [comment]
Same issue, using CPU only tensorflow install with num_layers set to 1.

```
Traceback (most recent call last):
  File "./train.py", line 15, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "./train.py", line 12, in main
    train()
  File "/home/user/testing/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 28, in train
    model = create_model(sess, forward_only=False)
  File "/home/user/testing/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 35, in create_model
    session.run(tf.initialize_all_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/GRUCell/Candidate/Linear/Bias': Could not satisfy explicit device specification '/gpu:0'
         [[Node: embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/GRUCell/Candidate/Linear/Bias = Variable[container="", dtype=DT_FLOAT, shape=[2048], shared_name="", _device="/gpu:0"]()]]
Caused by op u'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/GRUCell/Candidate/Linear/Bias', defined at:
  File "./train.py", line 15, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "./train.py", line 12, in main
    train()
  File "/home/user/testing/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 28, in train
    model = create_model(sess, forward_only=False)
  File "/home/user/testing/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 27, in create_model
    forward_only=forward_only)
  File "/home/user/testing/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 149, in __init__
    softmax_loss_function=softmax_loss_function)
   File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 629, in model_with_buckets
    bucket_decoder_inputs) #nick pay attention here -- you added bucket_states
  File "/home/user/testing/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 148, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "/home/user/testing/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 112, in seq2seq_f
    feed_previous=do_decode)
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 341, in embedding_attention_seq2seq
    temperature_decode = temperature_decode, temperature = temperature)
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 259, in embedding_attention_decoder
    temperature = temperature)
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 159, in attention_decoder
    cell_output, new_state = cell(x, hidden_state_input) #nick, changed this to your hidden state input
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/rnn_cell_enhanced.py", line 520, in __call__
    c = tf.tanh(linear.linear([inputs, r * state], self._num_units, True))
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/linear_enhanced.py", line 68, in linear
    initializer=tf.constant_initializer(bias_start))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 242, in get_variable
    trainable, collections)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 175, in get_variable
    self.reuse, trainable, collections)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 119, in get_variable
    collections=collections)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 210, in __init__
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 116, in variable_op
    container=container, shared_name=shared_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 334, in _variable
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
      original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()
```

**Comment by gaoxuesong** [comment]
Same issue

using CPU only tensorflow 0.6.0 install:
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl

set num_layers to 1 and run train.py got the error information:

```
root@tensorflow:~/tf_seq2seq_chatbot# python train.py
You are using the decoding_enhanced library!
Initializer Library -- Will add to this if necessary.
Unitary Linear has been imported
Preparing dialog data in /var/lib/tf_seq2seq_chatbot/data
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 2
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 2
Creating 1 layers of 2048 units.
use aggregation_method=2
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients.py:87: UserWarning: Converting sparse IndexedSlices to a dense Tensor with 163840000 elements. This may consume a large amount of memory.
  "This may consume a large amount of memory." % num_elements)
Created model with fresh parameters.
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 12, in main
    train()
  File "/root/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 28, in train
    model = create_model(sess, forward_only=False)
  File "/root/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 35, in create_model
    session.run(tf.initialize_all_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/GRUCell/Candidate/Linear/Bias': Could not satisfy explicit device specification '/gpu:0'
         [[Node: embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/GRUCell/Candidate/Linear/Bias = Variable[container="", dtype=DT_FLOAT, shape=[2048], shared_name="", _device="/gpu:0"]()]]
Caused by op u'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/GRUCell/Candidate/Linear/Bias', defined at:
  File "train.py", line 15, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 12, in main
    train()
  File "/root/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 28, in train
    model = create_model(sess, forward_only=False)
  File "/root/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 27, in create_model
    forward_only=forward_only)
  File "/root/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 149, in __init__
    softmax_loss_function=softmax_loss_function)
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 629, in model_with_buckets
    bucket_decoder_inputs) #nick pay attention here -- you added bucket_states
  File "/root/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 148, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "/root/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 112, in seq2seq_f
    feed_previous=do_decode)
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 341, in embedding_attention_seq2seq
    temperature_decode = temperature_decode, temperature = temperature)
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 259, in embedding_attention_decoder
    temperature = temperature)
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 159, in attention_decoder
    cell_output, new_state = cell(x, hidden_state_input) #nick, changed this to your hidden state input
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/rnn_cell_enhanced.py", line 520, in __call__
    c = tf.tanh(linear.linear([inputs, r * state], self._num_units, True))
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/linear_enhanced.py", line 68, in linear
    initializer=tf.constant_initializer(bias_start))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 242, in get_variable
    trainable, collections)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 175, in get_variable
    self.reuse, trainable, collections)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 119, in get_variable
    collections=collections)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 210, in __init__
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 116, in variable_op
    container=container, shared_name=shared_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 334, in _variable
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()
```

**Comment by geckom** [comment]
FIX:
Add config=tf.ConfigProto(allow_soft_placement=True) to tf.Sessions

Eg. sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))

Replace in files:
./tf_seq2seq_chatbot/lib/predict.py
./tf_seq2seq_chatbot/lib/train.py
./tf_seq2seq_chatbot/lib/chat.py

Should fix the problem

**Comment by nicolas-ivanov** [comment]
@nodgesoft thank you for your fix suggestion!
I'm gonna close the issue for now, but feel free to reopen it.

**Comment by sgaurav** [comment]
Can anyone please share time taken to train. I am on Macbook Pro, running for last 2 days and still stuck at 100k lines.

**Comment by nicolas-ivanov** [comment]
@sgaurav I didn't even try training my seq2seq model on CPU, cause in my opinion it's hopeless :)
Of course, you can diminish your training params, i.e. number of hidden layers, their dimensionality and the length of your data sequences, but whatever seq2seq you are dealing with, I'm sure it's just too weighty for your Macbook, despite it has Pro in its name... 

Training on GPU is usually ~80 times faster. And even on a powerful GPUs it's a matter of days to get any meaningful results with this model. So, you do the math )

In case you wish to jump on some GPU now, you may consider Amazon Web Services, they are quite good. According to the [price list](http://aws.amazon.com/ec2/pricing/) a small GPU instance would cost you approximately $20 a day.

And lastly, my tiny recommendation: if you have a question that doesn't relate to the topic of the current conversation, it's better to create a new issue. Ok?

**Comment by sgaurav** [comment]
Yes, AWS is what I am planning to move to. Mostly a g2.2xlarge.

My bad in not creating a new issue. @nodgesoft solution helped me run on my system and I ended up pasting question here. Thanks for pointing out.

**Comment by anantzoid** [comment]
@nicolas-ivanov @geckom After setting `tf.ConfigProto(allow_soft_placement=True)` I get the following error:

```
E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: AttrValue must not have reference type value of float_ref
     for attr 'tensor_type'
    ; NodeDef: proj_b/_6691 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_350991_proj_b", tensor_type=DT_FLOAT_REF, _device="/job:localhost/replica:0/task:0/cpu:0"](^gradients_2/concat_1, ^GradientDescent_2/update_proj_b/mul/_6693); Op<name=_Recv; signature= -> tensor:tensor_type; attr=tensor_type:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>
```

I think it's alloting cpu by default for calculating softmax.

**Comment by PKS2211** [comment]
I am using Jupyter Notebook and seeing some erratic behaviour. Sometime it works otherwise it gives me same error. Using tf.IntractiveSession instead of tf.Session be the culprit.

tf.ConfigProto(allow_soft_placement = True)
#sess = tf.Session(config = config)
#sess = tf.InteractiveSession(config = config)
