### ISSUE TITLE
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. -----tensorflow0.8

### ISSUE THREAD

**Issue by SeekPoint** [nicolas-ivanov/tf_seq2seq_chatbot#8]
envy@ub1404:~/os_pri/github/tf_seq2seq_chatbot$ python train.py
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
You are using the decoding_enhanced library!
Initializer Library -- Will add to this if necessary.
Unitary Linear has been imported
Preparing dialog data in /var/lib/tf_seq2seq_chatbot/data
Creating vocabulary /var/lib/tf_seq2seq_chatbot/data/vocab80000.in from data /var/lib/tf_seq2seq_chatbot/data/chat.in
  processing line 100000
  processing line 200000
  processing line 300000
Tokenizing data in /var/lib/tf_seq2seq_chatbot/data/chat.in
  tokenizing line 100000
  tokenizing line 200000
  tokenizing line 300000
Tokenizing data in /var/lib/tf_seq2seq_chatbot/data/chat_test.in
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.70GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
Creating 4 layers of 2048 units.
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 12, in main
    train()
  File "/home/envy/os_pri/github/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 28, in train
    model = create_model(sess, forward_only=False)
  File "/home/envy/os_pri/github/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 27, in create_model
    forward_only=forward_only)
  File "/home/envy/os_pri/github/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 149, in **init**
    softmax_loss_function=softmax_loss_function)
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 629, in model_with_buckets
  File "/home/envy/os_pri/github/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 148, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "/home/envy/os_pri/github/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 112, in seq2seq_f
    feed_previous=do_decode)
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 341, in embedding_attention_seq2seq
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 259, in embedding_attention_decoder
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 165, in attention_decoder
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/seq2seq_enhanced.py", line 112, in attention
  File "build/bdist.linux-x86_64/egg/rnn_enhancement/linear_enhanced.py", line 42, in linear
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 475, in **nonzero**
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.
envy@ub1404:~/os_pri/github/tf_seq2seq_chatbot$

**Comment by sodis** [comment]
same issue.
tensorflow 0.8, macbook pro

**Comment by maeda** [comment]
I don't know exactly why, but when you comment or remove that validation (https://github.com/nicolas-ivanov/Seq2Seq_Upgrade_TensorFlow/blob/master/rnn_enhancement/linear_enhanced.py#L44), this error not happen anymore.

I'm just testing this code, so I won't invest more time to investigate the reason. Anyway, I'm sharing to  unblock you.
